# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_4/lab_4.srcs/sources_1/ip/state_ila/state_ila.xci
# IP: The module: 'state_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_4/lab_4.srcs/sources_1/ip/state_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'state_ila'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_4/lab_4.srcs/sources_1/ip/state_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'state_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_4/lab_4.srcs/sources_1/ip/state_ila/state_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'state_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_4/lab_4.srcs/sources_1/ip/state_ila/state_ila.xci
# IP: The module: 'state_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_4/lab_4.srcs/sources_1/ip/state_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'state_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_4/lab_4.srcs/sources_1/ip/state_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'state_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_4/lab_4.srcs/sources_1/ip/state_ila/state_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'state_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
