#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 14 19:47:33 EDT 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto fd31f508cf2842b3a4631abc8fe23cc8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot top_level_l4_tb_behav xil_defaultlib.top_level_l4_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto fd31f508cf2842b3a4631abc8fe23cc8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot top_level_l4_tb_behav xil_defaultlib.top_level_l4_tb xil_defaultlib.glbl -log elaborate.log

