# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joselavariega/Desktop/6.111 Digital Systems Lab/final_proj_mydraft/final_proj_mydraft.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/final_proj_mydraft/final_proj_mydraft.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/joselavariega/Desktop/6.111 Digital Systems Lab/final_proj_mydraft/final_proj_mydraft.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/final_proj_mydraft/final_proj_mydraft.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
