# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_5_6111/lab_5_6111.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_5_6111/lab_5_6111.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_5_6111/lab_5_6111.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_5_6111/lab_5_6111.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_5_6111/lab_5_6111.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joselavariega/Desktop/6.111 Digital Systems Lab/lab_5_6111/lab_5_6111.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
